#!/usr/bin/env python3
"""Ollama-to-llama.cpp API bridge for baby-llm-nanny.

baby-llm-nanny expects Ollama's API (/api/generate, /api/tags).
llama.cpp server exposes an OpenAI-compatible API (/v1/chat/completions).
This bridge translates between them so baby-llm-nanny can screen
code generated by the llama.cpp + Gemma 4 E2B server.

Start the bridge, then run baby-llm-nanny with --host localhost --port <bridge_port>.

Usage:
    python3 nanny_bridge.py --llama-port 8080 --bridge-port 11434
"""

from __future__ import annotations

import argparse
import json
import urllib.request
import urllib.error
from http.server import HTTPServer, BaseHTTPRequestHandler

# Model name baby-llm-nanny will see
BRIDGE_MODEL_NAME = "gemma-4-e2b"


class BridgeHandler(BaseHTTPRequestHandler):
    llama_host: str = "127.0.0.1"
    llama_port: int = 8080

    def _json_response(self, data: dict, status: int = 200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _llama_url(self, path: str) -> str:
        return f"http://{self.llama_host}:{self.llama_port}{path}"

    def _llama_chat(self, prompt: str, system: str | None, options: dict) -> dict:
        """Call llama.cpp /v1/chat/completions and return Ollama-format response."""
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "messages": messages,
            "temperature": options.get("temperature", 0.0),
            "max_tokens": options.get("num_predict", 2048),
        }
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self._llama_url("/v1/chat/completions"),
            data=body,
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                data = json.loads(resp.read())
        except urllib.error.URLError as e:
            return {"response": "", "error": f"llama.cpp connection error: {e.reason}"}
        except Exception as e:
            return {"response": "", "error": f"llama.cpp error: {e}"}

        # Gemma 4 E2B is a thinking model: content has the answer,
        # reasoning_content has the thinking. We only pass content through.
        content = ""
        choices = data.get("choices", [])
        if choices:
            msg = choices[0].get("message", {})
            content = msg.get("content", "")

        usage = data.get("usage", {})
        return {
            "response": content,
            "eval_count": usage.get("completion_tokens", 0),
            "prompt_eval_count": usage.get("prompt_tokens", 0),
            "done": True,
        }

    def do_GET(self):
        if self.path == "/api/tags":
            # Pretend to be Ollama with one model
            self._json_response({
                "models": [{"name": BRIDGE_MODEL_NAME, "size": 0}]
            })
        else:
            self._json_response({"error": "not found"}, 404)

    def do_POST(self):
        if self.path == "/api/generate":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length) if length else b"{}"
            try:
                data = json.loads(body)
            except json.JSONDecodeError:
                self._json_response({"response": "", "error": "bad JSON"}, 400)
                return

            prompt = data.get("prompt", "")
            system = data.get("system")
            options = data.get("options", {})
            result = self._llama_chat(prompt, system, options)

            if "error" in result:
                self._json_response(result, 502)
            else:
                self._json_response(result)
        else:
            self._json_response({"error": "not found"}, 404)

    def log_message(self, format, *args):
        # Quiet logging — just errors
        if "502" in (args[1] if len(args) > 1 else ""):
            print(f"[bridge] {format % args}")


def main():
    parser = argparse.ArgumentParser(
        description="Ollama-to-llama.cpp API bridge for baby-llm-nanny"
    )
    parser.add_argument("--llama-host", default="127.0.0.1")
    parser.add_argument("--llama-port", type=int, default=8080)
    parser.add_argument("--bridge-host", default="127.0.0.1")
    parser.add_argument("--bridge-port", type=int, default=11434)
    args = parser.parse_args()

    BridgeHandler.llama_host = args.llama_host
    BridgeHandler.llama_port = args.llama_port

    server = HTTPServer((args.bridge_host, args.bridge_port), BridgeHandler)
    print(f"[bridge] Ollama API on {args.bridge_host}:{args.bridge_port}")
    print(f"[bridge] -> llama.cpp at {args.llama_host}:{args.llama_port}")
    print(f"[bridge] Model name: {BRIDGE_MODEL_NAME}")
    print("[bridge] Ready. Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[bridge] Stopped.")
        server.server_close()


if __name__ == "__main__":
    main()