#!/usr/bin/env python3
"""Ollama-to-llama.cpp API bridge with real-time deterministic code review.

baby-llm-nanny expects Ollama's API (/api/generate, /api/tags).
llama.cpp server exposes an OpenAI-compatible API (/v1/chat/completions).
This bridge translates between them so baby-llm-nanny can screen
code generated by the llama.cpp + Gemma 4 E2B server.

When --review is enabled, the bridge also intercepts every response,
detects Python code, and deterministically verifies it:
  1. Extracts code from markdown fences or bare def/class blocks
  2. Syntax-checks with py_compile
  3. (Optional) Executes against provided test cases
  4. If code fails, feeds the specific error back to the model for a retry
  5. Only returns the final verified response to the caller

Start the bridge, then run baby-llm-nanny with --host localhost --port <bridge_port>.

Usage:
    python3 nanny_bridge.py --llama-port 8080 --bridge-port 11434
    python3 nanny_bridge.py --llama-port 8080 --bridge-port 11434 --review
    python3 nanny_bridge.py --llama-port 8080 --bridge-port 11434 --review --max-fix-attempts 5
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import textwrap
import time
import urllib.request
import urllib.error
from http.server import HTTPServer, BaseHTTPRequestHandler

# Model name baby-llm-nanny will see
BRIDGE_MODEL_NAME = "gemma-4-e2b"


# ─────────────────────────────────────────────────────────────────────
# Real-time code detection and deterministic review
# ─────────────────────────────────────────────────────────────────────

def extract_code_blocks(text: str) -> list[dict]:
    """Extract Python code blocks from a model response.

    Returns a list of dicts: {"code": str, "start": int, "end": int, "source": str}
    where start/end are character offsets in the original text.

    Extraction order:
    1. ```python ... ``` markdown fences
    2. ``` ... ``` generic fences (if they look like Python)
    3. Bare def/class blocks (for models that don't use fences)
    """
    blocks = []

    # 1. Markdown fences with python label
    for m in re.finditer(r"```python\s*(.*?)\s*```", text, re.DOTALL):
        blocks.append({
            "code": textwrap.dedent(m.group(1)).strip(),
            "start": m.start(),
            "end": m.end(),
            "source": "python-fence",
        })

    # 2. Generic markdown fences (check if they look like Python)
    if not blocks:
        for m in re.finditer(r"```\s*(.*?)\s*```", text, re.DOTALL):
            code = textwrap.dedent(m.group(1)).strip()
            if _looks_like_python(code):
                blocks.append({
                    "code": code,
                    "start": m.start(),
                    "end": m.end(),
                    "source": "generic-fence",
                })

    # 3. Bare def/class blocks (no fences at all)
    if not blocks:
        # Match def/class at the start of a line, capture until next def/class or end
        pattern = r"((?:def\s+\w+|class\s+\w+).*?)(?=\ndef\s+\w+|\nclass\s+\w+|\Z)"
        for m in re.finditer(pattern, text, re.DOTALL):
            code = textwrap.dedent(m.group(1)).strip()
            if code and _looks_like_python(code):
                blocks.append({
                    "code": code,
                    "start": m.start(),
                    "end": m.end(),
                    "source": "bare-block",
                })

    return blocks


def _looks_like_python(code: str) -> bool:
    """Heuristic: does this text look like Python code?"""
    indicators = [
        r"^\s*def\s+\w+\s*\(",
        r"^\s*class\s+\w+",
        r"^\s*import\s+\w+",
        r"^\s*from\s+\w+\s+import",
        r"^\s*if\s+.*:\s*$",
        r"^\s*for\s+.*:\s*$",
        r"^\s*while\s+.*:\s*$",
        r"^\s*return\s+",
        r"^\s*print\s*\(",
    ]
    for line in code.split("\n"):
        for pat in indicators:
            if re.match(pat, line):
                return True
    return False


def syntax_check(code: str) -> tuple[bool, str]:
    """Syntax-check Python code using py_compile.

    Returns (ok, error_message). If ok is True, error_message is empty.
    """
    try:
        compile(code, "<bridge-review>", "exec")
        return True, ""
    except SyntaxError as e:
        return False, f"SyntaxError: {e.msg} (line {e.lineno})"
    except Exception as e:
        return False, f"Compile error: {e}"


def execute_code(code: str, timeout: int = 10) -> tuple[bool, str, str]:
    """Execute Python code in an isolated subprocess.

    Returns (ok, stdout, stderr). If ok is False, stderr has the error.
    """
    try:
        proc = subprocess.run(
            ["python3", "-c", code],
            capture_output=True, text=True, timeout=timeout,
            cwd="/tmp",
        )
        if proc.returncode != 0:
            return False, proc.stdout, proc.stderr[:1000] if proc.stderr else "(no stderr)"
        return True, proc.stdout, ""
    except subprocess.TimeoutExpired:
        return False, "", "Code execution timed out (10s)"
    except Exception as e:
        return False, "", f"Failed to execute: {e}"


def extract_function_name(code: str) -> str | None:
    """Try to extract the main function name from a code block."""
    m = re.search(r"def\s+(\w+)\s*\(", code)
    if m:
        return m.group(1)
    return None


def build_fix_feedback(code: str, errors: list[str], original_prompt: str) -> str:
    """Build a feedback prompt telling the model what went wrong."""
    feedback = f"""
Your previous code had the following errors:

"""
    for i, err in enumerate(errors):
        feedback += f"  {i+1}. {err}\n"

    feedback += f"""
Here is your previous code:
```python
{code}
```

Please fix the issues and provide the corrected code.
Return only the corrected Python code, no explanation.

Original task:
{original_prompt}
"""
    return feedback


def review_response(
    content: str,
    reasoning: str,
    original_prompt: str,
    messages: list[dict],
    llama_url: str,
    max_fix_attempts: int,
    timeout: int = 300,
) -> tuple[str, str, dict]:
    """Review a model response for code errors and auto-fix if needed.

    Args:
        content:          The model's response content (the answer).
        reasoning:        The model's reasoning_content (thinking tokens).
        original_prompt:  The user's original prompt.
        messages:         The original messages list (for re-querying).
        llama_url:        Full URL to llama.cpp /v1/chat/completions.
        max_fix_attempts: Max number of fix retries.
        timeout:          Request timeout for re-queries.

    Returns:
        (final_content, final_reasoning, review_info)
        review_info is a dict with:
          - "reviewed": bool (was code detected and reviewed?)
          - "attempts": int (total attempts including original)
          - "passed": bool (did code pass all checks?)
          - "errors": list[str] (errors found, empty if passed)
          - "fixes": list[str] (errors fixed by auto-retry, empty if none)
    """
    review_info = {
        "reviewed": False,
        "attempts": 0,
        "passed": False,
        "errors": [],
        "fixes": [],
    }

    blocks = extract_code_blocks(content)
    if not blocks:
        # No code detected — pass through unchanged
        return content, reasoning, review_info

    review_info["reviewed"] = True
    review_info["attempts"] = 1

    # Check all code blocks
    all_errors = []
    for block in blocks:
        code = block["code"]

        # 1. Syntax check
        ok, err = syntax_check(code)
        if not ok:
            all_errors.append(f"[{block['source']}] {err}")
            continue

        # 2. Execution test (import-level — just check it runs without error)
        # We don't call functions since we don't know the test cases,
        # but we can at least verify the module loads.
        ok_exec, stdout, stderr = execute_code(code, timeout=5)
        if not ok_exec:
            # Only flag as error if it's not just "no output" (which is fine
            # for a function definition that isn't called)
            if "named" in stderr and "is not defined" not in stderr:
                # Runtime error during import/definition
                all_errors.append(f"[{block['source']}] Runtime error: {stderr.strip()[:200]}")

    if not all_errors:
        review_info["passed"] = True
        return content, reasoning, review_info

    review_info["errors"] = all_errors

    # Auto-fix loop
    current_content = content
    current_reasoning = reasoning

    for attempt in range(max_fix_attempts):
        review_info["attempts"] += 1

        # Build feedback and re-query
        feedback = build_fix_feedback(
            "\n\n".join(b["code"] for b in blocks),
            all_errors,
            original_prompt,
        )

        # Replace the last user message with the feedback
        fix_messages = list(messages)  # copy
        if fix_messages and fix_messages[-1]["role"] == "user":
            fix_messages[-1] = {"role": "user", "content": feedback}
        else:
            fix_messages.append({"role": "user", "content": feedback})

        fix_payload = {
            "messages": fix_messages,
            "temperature": 0.0,  # deterministic for fixes
            "max_tokens": 2048,
        }
        body = json.dumps(fix_payload).encode("utf-8")
        req = urllib.request.Request(
            llama_url,
            data=body,
            headers={"Content-Type": "application/json"},
        )

        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                data = json.loads(resp.read())
        except Exception as e:
            # If re-query fails, return what we have with the errors noted
            review_info["fixes"].append(f"Fix attempt {attempt+1} failed: {e}")
            return current_content, current_reasoning, review_info

        choices = data.get("choices", [])
        if not choices:
            break

        msg = choices[0].get("message", {})
        current_content = msg.get("content", "")
        current_reasoning = msg.get("reasoning_content", "")

        # Re-check the fixed code
        new_blocks = extract_code_blocks(current_content)
        if not new_blocks:
            # Model didn't return code in the fix — give up
            review_info["fixes"].append(f"Fix attempt {attempt+1}: no code in response")
            break

        new_errors = []
        for block in new_blocks:
            code = block["code"]
            ok, err = syntax_check(code)
            if not ok:
                new_errors.append(f"[{block['source']}] {err}")
                continue
            ok_exec, _, stderr = execute_code(code, timeout=5)
            if not ok_exec and "named" in stderr and "is not defined" not in stderr:
                new_errors.append(f"[{block['source']}] Runtime error: {stderr.strip()[:200]}")

        if not new_errors:
            # Fixed!
            review_info["passed"] = True
            review_info["fixes"] = all_errors  # the errors that were fixed
            return current_content, current_reasoning, review_info

        all_errors = new_errors

    # Exhausted fix attempts
    return current_content, current_reasoning, review_info


# ─────────────────────────────────────────────────────────────────────
# HTTP bridge server
# ─────────────────────────────────────────────────────────────────────

class BridgeHandler(BaseHTTPRequestHandler):
    llama_host: str = "127.0.0.1"
    llama_port: int = 8080
    review_enabled: bool = False
    max_fix_attempts: int = 3
    # Stats
    _total_requests: int = 0
    _code_detected: int = 0
    _code_fixed: int = 0
    _code_passed_first_try: int = 0

    def _json_response(self, data: dict, status: int = 200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _llama_url(self, path: str) -> str:
        return f"http://{self.llama_host}:{self.llama_port}{path}"

    def _llama_chat(self, prompt: str, system: str | None, options: dict) -> dict:
        """Call llama.cpp /v1/chat/completions and return Ollama-format response."""
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "messages": messages,
            "temperature": options.get("temperature", 0.0),
            "max_tokens": options.get("num_predict", 2048),
        }
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self._llama_url("/v1/chat/completions"),
            data=body,
            headers={"Content-Type": "application/json"},
        )

        llama_url = self._llama_url("/v1/chat/completions")

        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                data = json.loads(resp.read())
        except urllib.error.URLError as e:
            return {"response": "", "error": f"llama.cpp connection error: {e.reason}"}
        except Exception as e:
            return {"response": "", "error": f"llama.cpp error: {e}"}

        # Gemma 4 E2B is a thinking model: content has the answer,
        # reasoning_content has the thinking. We only pass content through.
        content = ""
        reasoning = ""
        choices = data.get("choices", [])
        if choices:
            msg = choices[0].get("message", {})
            content = msg.get("content", "")
            reasoning = msg.get("reasoning_content", "")

        usage = data.get("usage", {})

        # ── Real-time code review ──
        if self.review_enabled and content:
            final_content, final_reasoning, review_info = review_response(
                content=content,
                reasoning=reasoning,
                original_prompt=prompt,
                messages=messages,
                llama_url=llama_url,
                max_fix_attempts=self.max_fix_attempts,
            )

            type(self)._total_requests += 1
            if review_info["reviewed"]:
                type(self)._code_detected += 1
                if review_info["passed"] and review_info["attempts"] == 1:
                    type(self)._code_passed_first_try += 1
                elif review_info["passed"] and review_info["attempts"] > 1:
                    type(self)._code_fixed += 1

                # Print review summary to stderr (visible in bridge log)
                status = "✅ PASS" if review_info["passed"] else "❌ FAIL"
                fix_note = ""
                if review_info["attempts"] > 1:
                    fix_note = f" (fixed in {review_info['attempts']} attempts)" if review_info["passed"] else f" (failed after {review_info['attempts']} attempts)"
                print(f"[review] {status}{fix_note} — {review_info['attempts']} attempt(s)", file=sys.stderr)
                if review_info["errors"]:
                    for err in review_info["errors"][:3]:
                        print(f"  error: {err}", file=sys.stderr)
                if review_info["fixes"]:
                    for fix in review_info["fixes"][:3]:
                        print(f"  fixed: {fix}", file=sys.stderr)

            content = final_content
            reasoning = final_reasoning

        return {
            "response": content,
            "eval_count": usage.get("completion_tokens", 0),
            "prompt_eval_count": usage.get("prompt_tokens", 0),
            "done": True,
        }

    def do_GET(self):
        if self.path == "/api/tags":
            self._json_response({
                "models": [{"name": BRIDGE_MODEL_NAME, "size": 0}]
            })
        elif self.path == "/bridge/stats":
            # Bridge statistics endpoint
            self._json_response({
                "total_requests": self._total_requests,
                "code_detected": self._code_detected,
                "code_passed_first_try": self._code_passed_first_try,
                "code_fixed_via_retry": self._code_fixed,
                "review_enabled": self.review_enabled,
                "max_fix_attempts": self.max_fix_attempts,
            })
        else:
            self._json_response({"error": "not found"}, 404)

    def do_POST(self):
        if self.path == "/api/generate":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length) if length else b"{}"
            try:
                data = json.loads(body)
            except json.JSONDecodeError:
                self._json_response({"response": "", "error": "bad JSON"}, 400)
                return

            prompt = data.get("prompt", "")
            system = data.get("system")
            options = data.get("options", {})
            result = self._llama_chat(prompt, system, options)

            if "error" in result:
                self._json_response(result, 502)
            else:
                self._json_response(result)
        else:
            self._json_response({"error": "not found"}, 404)

    def log_message(self, format, *args):
        # Quiet — only log errors
        if len(args) > 1 and "502" in str(args[1]):
            print(f"[bridge] {format % args}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Ollama-to-llama.cpp API bridge for baby-llm-nanny (with real-time code review)"
    )
    parser.add_argument("--llama-host", default="127.0.0.1")
    parser.add_argument("--llama-port", type=int, default=8080)
    parser.add_argument("--bridge-host", default="127.0.0.1")
    parser.add_argument("--bridge-port", type=int, default=11434)
    parser.add_argument("--review", action="store_true",
                        help="Enable real-time deterministic code review")
    parser.add_argument("--max-fix-attempts", type=int, default=3,
                        help="Max auto-fix retries when code fails (default: 3)")
    args = parser.parse_args()

    BridgeHandler.llama_host = args.llama_host
    BridgeHandler.llama_port = args.llama_port
    BridgeHandler.review_enabled = args.review
    BridgeHandler.max_fix_attempts = args.max_fix_attempts

    server = HTTPServer((args.bridge_host, args.bridge_port), BridgeHandler)
    print(f"[bridge] Ollama API on {args.bridge_host}:{args.bridge_port}", file=sys.stderr)
    print(f"[bridge] -> llama.cpp at {args.llama_host}:{args.llama_port}", file=sys.stderr)
    print(f"[bridge] Model name: {BRIDGE_MODEL_NAME}", file=sys.stderr)
    if args.review:
        print(f"[bridge] Real-time code review: ENABLED (max {args.max_fix_attempts} fix attempts)", file=sys.stderr)
    else:
        print(f"[bridge] Real-time code review: disabled (use --review to enable)", file=sys.stderr)
    print(f"[bridge] Stats: http://{args.bridge_host}:{args.bridge_port}/bridge/stats", file=sys.stderr)
    print(f"[bridge] Ready. Ctrl+C to stop.", file=sys.stderr)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[bridge] Stopped.", file=sys.stderr)
        server.server_close()


if __name__ == "__main__":
    main()